# config.toml
baseURL = 'http://sapsead.me/'
languageCode = 'en-us'
title = 'Nick Sapsead'
theme ='LoveIt'


[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"

[[menu.main]]
  name = "Blog"
  weight = 3
  url = "/posts"
