baseURL = "https://sapsead.me/"
title = "Nick Sapsead"
theme = "Loveit"

[params]
author = "Nick Sapsead"
description = "A Spot for my Ramblings"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3