# config.toml
baseURL = 'http://sapsead.me/'
languageCode = 'en-us'
title = 'Nick Sapsead'
theme ='LoveIt'

[module]
  [[module.imports]]
    path = "github.com/dillonzq/LoveIt"

[menu]
[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"

[[menu.main]]
  name = "Blog"
  weight = 3
  url = "/posts"

#[[menu.main]]
 # name = "buy me a Coffee"
  # weight = 4
 # url = "buymeacoffee.com/nsapsead"